"""empty message

Revision ID: 2ae1d7f321b7
Revises: 432bd67acb38
Create Date: 2021-03-05 13:35:34.553587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ae1d7f321b7'
down_revision = '432bd67acb38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('spells', 'attackType',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('spells', 'material',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.alter_column('spells', 'range',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('spells', 'range',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('spells', 'material',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.alter_column('spells', 'attackType',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    # ### end Alembic commands ###
